- name: deploying webserver
  hosts: web
  gather_facts: false
  tasks:
   - name: create the directory /tmp/exam24
     file:
      path: /tmp/exam24
      state: directory
   - name: copy file /etc/fstab into /tmp/exam24
     copy:
      src: /etc/fstab
      dest: /tmp/exam24
   - name: restart cronde
     service:
      name: crond
      state: restarted
   - name: installed httpd and vsftpd
     yum:
      name:
       - httpd
       - samba
      state: installed

